### ISSUE TITLE
CSS - homework1

### ISSUE THREAD

**Issue by bbandydd** [bonnieyu53/training_schedule#1]
# Header

- [x] INDOOR需使用h1，通常重要標題或關鍵字會用h1，而且一個網頁只會有一個h1
- [x] home～Contact那列不該單獨使用li，要用li就要用ul包起來，ul跟li應該只用於home～Contact那列
- [x] home～Contact那列加上hover變色效果
- [x] 選單被選擇要顯示不同顏色，通常會給.active class去換色
- [x] 移除shop icon的maring-top，header可以設定 align-items: center; 達到垂直置中

# Footer

- [x] 移除.bottomInfo的margin: 0 auto;，使用flex的justify-content:center即可，目前的justify-content:center沒用是因為有bug，需修正
- [x] 誤用li
- [x] 不該用br
- [x] input type=button可直接用button
- [x] fb, twitter icon結構需調整
- [x] input[type="email"]的calc(100% - 20px)有更好的做法

# Content

- [x] 不該用br
- [x] 誤用li
- [x] Kitchen、Decor、Bedroom應給class而不是針對全部的li
- [x] 圖片不該用css設定，寬高可用class設定
- [x] 左上onsale, new icon用class方式顯示
- [x] .description的background image不要用class設定

**Comment by bbandydd** [comment]
# Footer

- [ ] Contact Us多了沒用的</span>，多檢查是否有類似的

# Content

- [ ] class不該用.h657 .h468等，當height有變動時就會和項目對不起來
- [ ] .h170內包含background等設定，應該獨立一個class出來用

# SCSS

- [ ] 應該使用variable, mixin等等，利於之後修改

**Comment by chnbohwr** [comment]
![image](https://user-images.githubusercontent.com/6761222/36850844-baeba1c2-1da2-11e8-9d5b-aa375d99a7db.png)
這邊的 css 不盡理想，absolute 應該要包在 relative 裡面

**Comment by chnbohwr** [comment]
ok, please close this issue

**Comment by bonnieyu53** [comment]
Hyman 建議：
可以依照  DECOR / KITCHEN / BEDROOM  分成三組，有利於串資料
