### ISSUE TITLE
CSS-homework4

### ISSUE THREAD

**Issue by chnbohwr** [bonnieyu53/training_schedule#4]
![image](https://user-images.githubusercontent.com/6761222/36886082-7867ae62-1e25-11e8-8841-1eb7cdb6989d.png)
元素之間的隔開不要用 padding 要用 margin 

---

body 高度不要設定 100%

---

![image](https://user-images.githubusercontent.com/6761222/36886109-9de3dd50-1e25-11e8-96a9-77fdbd9c51a3.png)
顏色跟圖不同

---

![image](https://user-images.githubusercontent.com/6761222/36886158-e1fbe4b0-1e25-11e8-906d-09f279246287.png)
圖不是純黑的

---

![image](https://user-images.githubusercontent.com/6761222/36886205-1b7ed0b2-1e26-11e8-80db-e4c4e09a0c7d.png)
取名 box 不是很優

---

![image](https://user-images.githubusercontent.com/6761222/36886282-95f0e7b8-1e26-11e8-8743-0e3985083708.png)

![image](https://user-images.githubusercontent.com/6761222/36886364-f9edc934-1e26-11e8-8403-705a4c6c346b.png)

幫忙看一下這兩個地方是否有過度包裝，若沒有就不用改

---

![image](https://user-images.githubusercontent.com/6761222/36886464-7d317ae8-1e27-11e8-81bd-333a6db4f233.png)

photo 可以用 background 方式放進去 flexslider 裡面，而 more 就可以不用 absolute 排版了。

---

（純粹思考）假設你想把這個網站當作樣板去賣錢，你的客戶想要把黑色的部分全部改成粉紅色，這時候要考慮把網站的主要色彩，主要文字顏色，抽成變數。

**Comment by bonnieyu53** [comment]
finish issue

**Comment by chnbohwr** [comment]
我打開以後有點問題哦 在幫忙檢查一下

![image](https://user-images.githubusercontent.com/6761222/36892804-e5ea3552-1e40-11e8-84b6-123e8a7007d3.png)

**Comment by bonnieyu53** [comment]
改掉box名稱忘了把CSS標籤一起改掉 ...
修改完畢

**Comment by chnbohwr** [comment]
ok

**Comment by bbandydd** [comment]
- [ ] 和issue2一樣，div class=toplink感覺多包了一層，可直接把class=toplink放在ul就好
- [ ] 裡面的數量請嘗試用css呈現，日後如果要用JS控制才可以用
![2018-03-04 7 04 54](https://user-images.githubusercontent.com/11688424/36944844-f3c78982-1fde-11e8-907d-b430c1b3307d.png)
- [ ] photo的圖片放到flexslider的background比較好
- [ ] more感覺可以直接給height，用line-height去撐開怪怪的
- [ ] bottomlink使用justify-content: space-around 沒用，因為三個元素都使用flex:1去撐開了
- [ ] 兩個元素間的互推，通常都是由上往下推，上面的元素margin-bottom去推開下面，所以應該是title用margin往下推article，這是一個習慣，看到中間有間隔就知道是由上往下推

**Comment by bonnieyu53** [comment]
finish
