### ISSUE TITLE
JS - String & Number

### ISSUE THREAD

**Issue by bbandydd** [bonnieyu53/training_schedule#6]
## 1

- [x] 請好好了解forEach的用法， (compare[indexj] !== allStrs[indexi][indexj]) 不該出現這種寫法
- [x] 請處理好例外狀況，目前未傳入參數或格式錯誤會出錯

## 3

- [x] 請處理好例外狀況，目前未傳入參數或格式錯誤會出錯

## 4

- [x] 有比while更適合的用法

## 5

- [x] 請處理好例外狀況，目前未傳入參數或格式錯誤會出錯

## 6

- [x] 請自己實作十進制轉二進制
- [x] 請處理好例外狀況，目前未傳入參數或格式錯誤會出錯
- [x] while有更好的作法，不需用到i，請修改

## 7

- [x] 請處理好例外狀況，目前未傳入參數或格式錯誤會出錯
- [x] 請統一回傳格式
<img width="116" alt="2018-03-08 2 43 14" src="https://user-images.githubusercontent.com/11688424/37137050-15142408-22df-11e8-93d5-40dbfcfc88dd.png">

**Comment by bonnieyu53** [comment]
完成

**Comment by bbandydd** [comment]
## 6

- [ ] 回傳格式錯誤，請修正
![2018-03-08 11 25 35](https://user-images.githubusercontent.com/11688424/37159145-0390f24e-2328-11e8-85db-87b857e427c0.png)
- [ ] 請處理好例外狀況，目前未傳入參數或格式錯誤會出錯
